version: "3"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
virtualbrowsers:
- name: hcp
  url: https://portal.cloud.hashicorp.com
virtualmachines:
- name: workstation
  image: ubuntu-os-cloud/ubuntu-2204-lts
  shell: bash
  machine_type: n1-standard-2
- name: windows
  image: instruqt/windows-server
  machine_type: n1-standard-2
aws_accounts:
- name: AWS-account
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess
