#!/bin/sh


until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done


terraform -chdir=hcp-deploy destroy -auto-approve

exit 0