#!/bin/sh

source /etc/profile.d/instruqt-env.sh

git clone https://github.com/dannyjknights/hcpb-secure-access-instruqt.git

#Define variables for Terraform
echo 'export TF_VAR_rdp_admin_username=SuperSecretBoundary' >> /etc/profile.d/instruqt-env.sh
echo 'export TF_VAR_s3_bucket_name=hcpb' >> /etc/profile.d/instruqt-env.sh
echo 'export TF_VAR_db_name=workshop_postgres' >> /etc/profile.d/instruqt-env.sh
echo 'export TF_VAR_db_password=workshop_UhFs5372Gjsbsbvgw' >> /etc/profile.d/instruqt-env.sh
echo 'export TF_VAR_db_username=workshop_user' >> /etc/profile.d/instruqt-env.sh
echo 'export TF_VAR_rdp_admin_pass=784b@!=dsgRGJjldEs' >> /etc/profile.d/instruqt-env.sh
echo "export TF_VAR_aws_access=$AWS_ACCESS_KEY_ID" >> /etc/profile.d/instruqt-env.sh
echo "export TF_VAR_aws_secret=$AWS_SECRET_ACCESS_KEY" >> /etc/profile.d/instruqt-env.sh
echo 'export AWS_ACCESS_KEY_ID="'$AWS_ACCESS_KEY_ID'"' >> /etc/profile.d/instruqt-env.sh
echo 'export AWS_SECRET_ACCESS_KEY="'$AWS_SECRET_ACCESS_KEY'"' >> /etc/profile.d/instruqt-env.sh


#Variables for Terraform, which are sourced from outputs of the config that has deployed the Boundary and Vault clusters
echo 'export VAULT_ADDR=$(terraform -chdir=hcp-deploy output -raw vault_addr)' >> /etc/profile.d/instruqt-env.sh 
echo 'export TF_VAR_vault_addr=$(terraform -chdir=hcp-deploy output -raw vault_addr)' >> /etc/profile.d/instruqt-env.sh 
echo 'export TF_VAR_vault_token=$(terraform -chdir=hcp-deploy output -raw vault_token)' >> /etc/profile.d/instruqt-env.sh 
echo 'export VAULT_TOKEN=$(terraform -chdir=hcp-deploy output -raw vault_token)' >> /etc/profile.d/instruqt-env.sh 
echo 'export TF_VAR_boundary_addr=$(terraform -chdir=hcp-deploy output -raw boundary_addr)' >> /etc/profile.d/instruqt-env.sh 


source /etc/profile.d/instruqt-env.sh

# export TF_VAR_aws_access=$AWS_ACCESS_KEY_ID
# export TF_VAR_aws_secret=$AWS_SECRET_ACCESS_KEY
# terraform -chdir=hcpb-secure-access init
# terraform -chdir=hcpb-secure-access apply -auto-approve

exit 0 







