#!/bin/sh


until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

source /etc/profile.d/instruqt-env.sh

apt-get update && sudo apt-get install -y gnupg software-properties-common

apt-get install wget

wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
apt update && apt install terraform
apt install boundary
apt install postgresql-client

#Install VSCode
curl -fsSL https://code-server.dev/install.sh | sh


mkdir -p /root/.local/share/code-server/User

cat > /root/.local/share/code-server/User/settings.json <<-EOF
{
    "workbench.colorTheme": "Default Dark+",
    "workbench.startupEditor": "none",
    "security.workspace.trust.enabled": false,
}
EOF

# Start Code Server
sudo systemctl enable --now code-server@$USER

############# install PASS, create GPG keys and initiate PASS with GPG key

# Install pass
sudo apt-get update
sudo apt-get install -y pass gnupg

# Generate GPG key
cat >gen-key-script <<EOF
%no-protection
Key-Type: default
Subkey-Type: default
Name-Real: Your Name
Name-Comment: pass init
Name-Email: email@example.com
Expire-Date: 0
EOF

gpg --batch --generate-key gen-key-script
rm gen-key-script

# Get the GPG key ID
GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep 'sec' | awk '{print $2}' | sed -e 's/.*\///')

# Initialize pass with the GPG key ID
pass init $GPG_KEY_ID

exit 0