#!/bin/bash

# store the output
output=$(terraform -chdir=hcp-deploy output -raw boundary_addr)

# Check if the output starts with "https://"
if [[ $output == https://* ]]; then
    exit 0
else 
    fail-message "Resources not deployed yet. Please wait until the terraform apply is complete."
    exit 1
fi